SET NUMERIC_ROUNDABORT OFF
GO
SET XACT_ABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
BEGIN TRANSACTION
ALTER TABLE [dbo].[Jobs] DROP CONSTRAINT [FK_Jobs_ToUsers]
INSERT INTO [dbo].[Users] ([Username], [Password], [FullName]) VALUES (N'Admin', N'Password', N'Site Administrator')
SET IDENTITY_INSERT [dbo].[Jobs] ON
INSERT INTO [dbo].[Jobs] ([MbcJobNo], [ClientJobNo], [Priority], [ClientName], [CurrentStatus], [OrderType], [SitePhoneNo], [Problem], [UserName], [Notes], [ArrivalTime], [DepartureTime], [MaterialsUsed], [CostsOfMaterials], [MaterialsRequired], [DurationToCompletion], [EnteredBy]) VALUES (2, 3511928, 1, N'Leicester Markfield', N'Quote/Uplift', N'CAPEX', N'08719846083', N'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', N'Admin', NULL, '20141206 00:00:00.000', '20141207 00:00:00.000', N'mats used', N'brought', N'req', N'2 hours', N'Craig Leech')
INSERT INTO [dbo].[Jobs] ([MbcJobNo], [ClientJobNo], [Priority], [ClientName], [CurrentStatus], [OrderType], [SitePhoneNo], [Problem], [UserName], [Notes], [ArrivalTime], [DepartureTime], [MaterialsUsed], [CostsOfMaterials], [MaterialsRequired], [DurationToCompletion], [EnteredBy]) VALUES (3, 3511929, 2, N'Markfield', N'Quote/Uplift', N'CAPEX', N'01234567898', N'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', N'Admin', N'There are some notes here', NULL, NULL, NULL, NULL, NULL, NULL, N'Craig Leech')
INSERT INTO [dbo].[Jobs] ([MbcJobNo], [ClientJobNo], [Priority], [ClientName], [CurrentStatus], [OrderType], [SitePhoneNo], [Problem], [UserName], [Notes], [ArrivalTime], [DepartureTime], [MaterialsUsed], [CostsOfMaterials], [MaterialsRequired], [DurationToCompletion], [EnteredBy]) VALUES (4, 3511930, 3, N'Leicester', N'Quote/Uplift', N'CAPEX', N'09876543212', N'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', N'Admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'Craig Leech')
SET IDENTITY_INSERT [dbo].[Jobs] OFF
ALTER TABLE [dbo].[Jobs]
    ADD CONSTRAINT [FK_Jobs_ToUsers] FOREIGN KEY ([UserName]) REFERENCES [dbo].[Users] ([Username])
COMMIT TRANSACTION