//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCFM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMHelpdeskSQLV4Entities : DbContext
    {
        public string Subcontractor;
        public FMHelpdeskSQLV4Entities()
            : base("name=FMHelpdeskSQLV4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<callOutFee> callOutFees { get; set; }
        public virtual DbSet<callOutRate> callOutRates { get; set; }
        public virtual DbSet<Current_Status> Current_Status { get; set; }
        public virtual DbSet<FMIncident> FMIncidents { get; set; }
        public virtual DbSet<FMIncidentsFM261> FMIncidentsFM261 { get; set; }
        public virtual DbSet<initialCallOut> initialCallOuts { get; set; }
        public virtual DbSet<jobLimit> jobLimits { get; set; }
        public virtual DbSet<little_chef> little_chef { get; set; }
        public virtual DbSet<Order_Type> Order_Types { get; set; }
        public virtual DbSet<primaryCallOutFee> primaryCallOutFees { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<ReActiveAddress> ReActiveAddresses { get; set; }
        public virtual DbSet<ResponseTime> ResponseTimes { get; set; }
        public virtual DbSet<secondaryCallOutFee> secondaryCallOutFees { get; set; }
        public virtual DbSet<Subcontractor> Subcontractors { get; set; }
        public virtual DbSet<Switchboard_Item> Switchboard_Items { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Travelodge> Travelodges { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<reactiveCallOut> reactiveCallOuts { get; set; }
        public virtual DbSet<qryOpenCall> qryOpenCalls { get; set; }
        public virtual DbSet<openCallsKevinDaley> openCallsKevinDaleys { get; set; }
    }
}
