//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCFM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class little_chef
    {
        public int MBC_Job_No { get; set; }
        public string Client_Job_No { get; set; }
        public string JobAddress { get; set; }
        public string OrderType { get; set; }
        public string Trade { get; set; }
        public string EnteredBy { get; set; }
        public string Date { get; set; }
        public string ReportedBy { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ResponseTime { get; set; }
        public Nullable<System.DateTime> RequiredBy { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string SubContractor { get; set; }
        public string Note { get; set; }
        public string AddNewNotes { get; set; }
        public string Problem { get; set; }
        public Nullable<System.DateTime> todaysDate { get; set; }
        public string timeOnSite { get; set; }
        public string timeOffSite { get; set; }
        public Nullable<decimal> materials { get; set; }
        public Nullable<decimal> labour { get; set; }
        public Nullable<decimal> totalCost { get; set; }
        public string currentStatus { get; set; }
        public string costingNotes { get; set; }
        public Nullable<decimal> subContractorMaterials { get; set; }
        public Nullable<decimal> subContractorlabour { get; set; }
        public Nullable<decimal> subContractorcosts { get; set; }
        public string siteName { get; set; }
        public string siteAddress { get; set; }
        public string siteAddress2 { get; set; }
        public string siteStreet { get; set; }
        public string siteTown { get; set; }
        public string siteCounty { get; set; }
        public string sitePostCode { get; set; }
        public string Invoiced { get; set; }
        public string jobLimits { get; set; }
        public string InvoiceAddress { get; set; }
        public string sitePhone { get; set; }
        public Nullable<decimal> invoiceTotal { get; set; }
        public Nullable<decimal> materialsProfit { get; set; }
        public Nullable<decimal> subContractorProfit { get; set; }
        public string subContractorInvoiceNumber { get; set; }
        public Nullable<System.DateTime> subContractorInvoiceDate { get; set; }
        public string subContractorInvoicePaid { get; set; }
    }
}
