//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCFM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryOpenCall
    {
        public int MBC_Job_No { get; set; }
        public string Client_Job_No { get; set; }
        public string siteName { get; set; }
        public Nullable<int> Priority { get; set; }
        public string OrderType { get; set; }
        public string currentStatus { get; set; }
        public string SubContractor { get; set; }
    }
}
