//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCFM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcontractor
    {
        public string SubContractor1 { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Town_City { get; set; }
        public string County { get; set; }
        public string PostCode { get; set; }
        public string Email_Address { get; set; }
        public string Phone_No { get; set; }
    }
}
